// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCommonAreaCountry = factory.Slicex[*OfficialCommonAreaCountry]

func NewOfficialCommonAreaCountry(ctx echo.Context) *OfficialCommonAreaCountry {
	m := &OfficialCommonAreaCountry{}
	m.SetContext(ctx)
	return m
}

// OfficialCommonAreaCountry 国家
type OfficialCommonAreaCountry struct {
	base    factory.Base
	objects []*OfficialCommonAreaCountry

	Id       uint   `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	Abbr     string `db:"abbr" bson:"abbr" comment:"国家缩写" json:"abbr" xml:"abbr"`
	Name     string `db:"name" bson:"name" comment:"名称" json:"name" xml:"name"`
	Short    string `db:"short" bson:"short" comment:"简称" json:"short" xml:"short"`
	Code     string `db:"code" bson:"code" comment:"国家码" json:"code" xml:"code"`
	Lng      string `db:"lng" bson:"lng" comment:"经度" json:"lng" xml:"lng"`
	Lat      string `db:"lat" bson:"lat" comment:"纬度" json:"lat" xml:"lat"`
	Sort     int    `db:"sort" bson:"sort" comment:"序号" json:"sort" xml:"sort"`
	Disabled string `db:"disabled" bson:"disabled" comment:"是否禁用" json:"disabled" xml:"disabled"`
}

// - base function

func (a *OfficialCommonAreaCountry) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCommonAreaCountry) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCommonAreaCountry) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCommonAreaCountry) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCommonAreaCountry) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCommonAreaCountry) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCommonAreaCountry) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCommonAreaCountry) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCommonAreaCountry) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCommonAreaCountry) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCommonAreaCountry) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCommonAreaCountry) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCommonAreaCountry) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCommonAreaCountry) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCommonAreaCountry) Objects() []*OfficialCommonAreaCountry {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCommonAreaCountry) XObjects() Slice_OfficialCommonAreaCountry {
	return Slice_OfficialCommonAreaCountry(a.Objects())
}

func (a *OfficialCommonAreaCountry) NewObjects() factory.Ranger {
	return &Slice_OfficialCommonAreaCountry{}
}

func (a *OfficialCommonAreaCountry) InitObjects() *[]*OfficialCommonAreaCountry {
	a.objects = []*OfficialCommonAreaCountry{}
	return &a.objects
}

func (a *OfficialCommonAreaCountry) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCommonAreaCountry) Short_() string {
	return "official_common_area_country"
}

func (a *OfficialCommonAreaCountry) Struct_() string {
	return "OfficialCommonAreaCountry"
}

func (a *OfficialCommonAreaCountry) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCommonAreaCountry{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *OfficialCommonAreaCountry) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *OfficialCommonAreaCountry) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *OfficialCommonAreaCountry) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCommonAreaCountry) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCommonAreaCountry:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCommonAreaCountry(*v))
		case []*OfficialCommonAreaCountry:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCommonAreaCountry(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCommonAreaCountry) GroupBy(keyField string, inputRows ...[]*OfficialCommonAreaCountry) map[string][]*OfficialCommonAreaCountry {
	var rows Slice_OfficialCommonAreaCountry
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonAreaCountry(inputRows[0])
	} else {
		rows = Slice_OfficialCommonAreaCountry(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCommonAreaCountry) KeyBy(keyField string, inputRows ...[]*OfficialCommonAreaCountry) map[string]*OfficialCommonAreaCountry {
	var rows Slice_OfficialCommonAreaCountry
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonAreaCountry(inputRows[0])
	} else {
		rows = Slice_OfficialCommonAreaCountry(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCommonAreaCountry) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCommonAreaCountry) param.Store {
	var rows Slice_OfficialCommonAreaCountry
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonAreaCountry(inputRows[0])
	} else {
		rows = Slice_OfficialCommonAreaCountry(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCommonAreaCountry) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCommonAreaCountry:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCommonAreaCountry(*v))
		case []*OfficialCommonAreaCountry:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCommonAreaCountry(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCommonAreaCountry) Insert() (pk interface{}, err error) {
	a.Id = 0
	if len(a.Abbr) == 0 {
		a.Abbr = "CN"
	}
	if len(a.Code) == 0 {
		a.Code = "86"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *OfficialCommonAreaCountry) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if len(a.Abbr) == 0 {
		a.Abbr = "CN"
	}
	if len(a.Code) == 0 {
		a.Code = "86"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *OfficialCommonAreaCountry) GetDiffColumns(old *OfficialCommonAreaCountry) (changedCols []interface{}) {

	if old.Id != a.Id {
		changedCols = append(changedCols, `id`)
	}

	if old.Abbr != a.Abbr {
		changedCols = append(changedCols, `abbr`)
	}

	if old.Name != a.Name {
		changedCols = append(changedCols, `name`)
	}

	if old.Short != a.Short {
		changedCols = append(changedCols, `short`)
	}

	if old.Code != a.Code {
		changedCols = append(changedCols, `code`)
	}

	if old.Lng != a.Lng {
		changedCols = append(changedCols, `lng`)
	}

	if old.Lat != a.Lat {
		changedCols = append(changedCols, `lat`)
	}

	if old.Sort != a.Sort {
		changedCols = append(changedCols, `sort`)
	}

	if old.Disabled != a.Disabled {
		changedCols = append(changedCols, `disabled`)
	}

	return
}

func (a *OfficialCommonAreaCountry) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if len(a.Abbr) == 0 {
		a.Abbr = "CN"
	}
	if len(a.Code) == 0 {
		a.Code = "86"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *OfficialCommonAreaCountry) Save(old *OfficialCommonAreaCountry, args ...interface{}) (affected int64, err error) {

	if len(a.Abbr) == 0 {
		a.Abbr = "CN"
	}
	if len(a.Code) == 0 {
		a.Code = "86"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if old == nil {
		old = NewOfficialCommonAreaCountry(a.Context())
		old.CtxFrom(a)
		if err = old.Get(nil, args...); err != nil {
			return
		}
	}
	changedCols := a.GetDiffColumns(old)
	if len(changedCols) == 0 {
		return
	}
	mw := func(r db.Result) db.Result {
		return r.Select(changedCols...).Limit(1)
	}
	return a.Updatex(mw, args...)
}

func (a *OfficialCommonAreaCountry) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {

	if len(a.Abbr) == 0 {
		a.Abbr = "CN"
	}
	if len(a.Code) == 0 {
		a.Code = "86"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialCommonAreaCountry) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {

	if len(a.Abbr) == 0 {
		a.Abbr = "CN"
	}
	if len(a.Code) == 0 {
		a.Code = "86"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialCommonAreaCountry) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCommonAreaCountry) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCommonAreaCountry) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["abbr"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["abbr"] = "CN"
		}
	}
	if val, ok := kvset["code"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["code"] = "86"
		}
	}
	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *OfficialCommonAreaCountry) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["abbr"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["abbr"] = "CN"
		}
	}
	if val, ok := kvset["code"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["code"] = "86"
		}
	}
	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *OfficialCommonAreaCountry) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCommonAreaCountry) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		if len(a.Abbr) == 0 {
			a.Abbr = "CN"
		}
		if len(a.Code) == 0 {
			a.Code = "86"
		}
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		a.Id = 0
		if len(a.Abbr) == 0 {
			a.Abbr = "CN"
		}
		if len(a.Code) == 0 {
			a.Code = "86"
		}
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *OfficialCommonAreaCountry) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *OfficialCommonAreaCountry) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *OfficialCommonAreaCountry) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCommonAreaCountry) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCommonAreaCountry) Reset() *OfficialCommonAreaCountry {
	a.Id = 0
	a.Abbr = ``
	a.Name = ``
	a.Short = ``
	a.Code = ``
	a.Lng = ``
	a.Lat = ``
	a.Sort = 0
	a.Disabled = ``
	return a
}

func (a *OfficialCommonAreaCountry) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["Abbr"] = a.Abbr
		r["Name"] = a.Name
		r["Short"] = a.Short
		r["Code"] = a.Code
		r["Lng"] = a.Lng
		r["Lat"] = a.Lat
		r["Sort"] = a.Sort
		r["Disabled"] = a.Disabled
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "Abbr":
			r["Abbr"] = a.Abbr
		case "Name":
			r["Name"] = a.Name
		case "Short":
			r["Short"] = a.Short
		case "Code":
			r["Code"] = a.Code
		case "Lng":
			r["Lng"] = a.Lng
		case "Lat":
			r["Lat"] = a.Lat
		case "Sort":
			r["Sort"] = a.Sort
		case "Disabled":
			r["Disabled"] = a.Disabled
		}
	}
	return r
}

func (a *OfficialCommonAreaCountry) Clone() *OfficialCommonAreaCountry {
	cloned := OfficialCommonAreaCountry{Id: a.Id, Abbr: a.Abbr, Name: a.Name, Short: a.Short, Code: a.Code, Lng: a.Lng, Lat: a.Lat, Sort: a.Sort, Disabled: a.Disabled}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *OfficialCommonAreaCountry) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "id":
			a.Id = param.AsUint(value)
		case "abbr":
			a.Abbr = param.AsString(value)
		case "name":
			a.Name = param.AsString(value)
		case "short":
			a.Short = param.AsString(value)
		case "code":
			a.Code = param.AsString(value)
		case "lng":
			a.Lng = param.AsString(value)
		case "lat":
			a.Lat = param.AsString(value)
		case "sort":
			a.Sort = param.AsInt(value)
		case "disabled":
			a.Disabled = param.AsString(value)
		}
	}
}

func (a *OfficialCommonAreaCountry) GetField(field string) interface{} {
	switch field {
	case "Id":
		return a.Id
	case "Abbr":
		return a.Abbr
	case "Name":
		return a.Name
	case "Short":
		return a.Short
	case "Code":
		return a.Code
	case "Lng":
		return a.Lng
	case "Lat":
		return a.Lat
	case "Sort":
		return a.Sort
	case "Disabled":
		return a.Disabled
	default:
		return nil
	}
}

func (a *OfficialCommonAreaCountry) GetAllFieldNames() []string {
	return []string{
		"Id",
		"Abbr",
		"Name",
		"Short",
		"Code",
		"Lng",
		"Lat",
		"Sort",
		"Disabled",
	}
}

func (a *OfficialCommonAreaCountry) HasField(field string) bool {
	switch field {
	case "Id":
		return true
	case "Abbr":
		return true
	case "Name":
		return true
	case "Short":
		return true
	case "Code":
		return true
	case "Lng":
		return true
	case "Lat":
		return true
	case "Sort":
		return true
	case "Disabled":
		return true
	default:
		return false
	}
}

func (a *OfficialCommonAreaCountry) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint(vv)
		case "Abbr":
			a.Abbr = param.AsString(vv)
		case "Name":
			a.Name = param.AsString(vv)
		case "Short":
			a.Short = param.AsString(vv)
		case "Code":
			a.Code = param.AsString(vv)
		case "Lng":
			a.Lng = param.AsString(vv)
		case "Lat":
			a.Lat = param.AsString(vv)
		case "Sort":
			a.Sort = param.AsInt(vv)
		case "Disabled":
			a.Disabled = param.AsString(vv)
		}
	}
}

func (a *OfficialCommonAreaCountry) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["abbr"] = a.Abbr
		r["name"] = a.Name
		r["short"] = a.Short
		r["code"] = a.Code
		r["lng"] = a.Lng
		r["lat"] = a.Lat
		r["sort"] = a.Sort
		r["disabled"] = a.Disabled
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "abbr":
			r["abbr"] = a.Abbr
		case "name":
			r["name"] = a.Name
		case "short":
			r["short"] = a.Short
		case "code":
			r["code"] = a.Code
		case "lng":
			r["lng"] = a.Lng
		case "lat":
			r["lat"] = a.Lat
		case "sort":
			r["sort"] = a.Sort
		case "disabled":
			r["disabled"] = a.Disabled
		}
	}
	return r
}

func (a *OfficialCommonAreaCountry) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *OfficialCommonAreaCountry) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *OfficialCommonAreaCountry) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *OfficialCommonAreaCountry) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *OfficialCommonAreaCountry) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *OfficialCommonAreaCountry) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *OfficialCommonAreaCountry) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
