// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialI18nResource = factory.Slicex[*OfficialI18nResource]

func NewOfficialI18nResource(ctx echo.Context) *OfficialI18nResource {
	m := &OfficialI18nResource{}
	m.SetContext(ctx)
	return m
}

// OfficialI18nResource 多语言key资源
type OfficialI18nResource struct {
	base    factory.Base
	objects []*OfficialI18nResource

	Id   uint   `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	Code string `db:"code" bson:"code" comment:"表名.字段名" json:"code" xml:"code"`
}

// - base function

func (a *OfficialI18nResource) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialI18nResource) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialI18nResource) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialI18nResource) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialI18nResource) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialI18nResource) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialI18nResource) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialI18nResource) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialI18nResource) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialI18nResource) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialI18nResource) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialI18nResource) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialI18nResource) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialI18nResource) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialI18nResource) Objects() []*OfficialI18nResource {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialI18nResource) XObjects() Slice_OfficialI18nResource {
	return Slice_OfficialI18nResource(a.Objects())
}

func (a *OfficialI18nResource) NewObjects() factory.Ranger {
	return &Slice_OfficialI18nResource{}
}

func (a *OfficialI18nResource) InitObjects() *[]*OfficialI18nResource {
	a.objects = []*OfficialI18nResource{}
	return &a.objects
}

func (a *OfficialI18nResource) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialI18nResource) Short_() string {
	return "official_i18n_resource"
}

func (a *OfficialI18nResource) Struct_() string {
	return "OfficialI18nResource"
}

func (a *OfficialI18nResource) Name_() string {
	b := a
	if b == nil {
		b = &OfficialI18nResource{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *OfficialI18nResource) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *OfficialI18nResource) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *OfficialI18nResource) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialI18nResource) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialI18nResource:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialI18nResource(*v))
		case []*OfficialI18nResource:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialI18nResource(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialI18nResource) GroupBy(keyField string, inputRows ...[]*OfficialI18nResource) map[string][]*OfficialI18nResource {
	var rows Slice_OfficialI18nResource
	if len(inputRows) > 0 {
		rows = Slice_OfficialI18nResource(inputRows[0])
	} else {
		rows = Slice_OfficialI18nResource(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialI18nResource) KeyBy(keyField string, inputRows ...[]*OfficialI18nResource) map[string]*OfficialI18nResource {
	var rows Slice_OfficialI18nResource
	if len(inputRows) > 0 {
		rows = Slice_OfficialI18nResource(inputRows[0])
	} else {
		rows = Slice_OfficialI18nResource(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialI18nResource) AsKV(keyField string, valueField string, inputRows ...[]*OfficialI18nResource) param.Store {
	var rows Slice_OfficialI18nResource
	if len(inputRows) > 0 {
		rows = Slice_OfficialI18nResource(inputRows[0])
	} else {
		rows = Slice_OfficialI18nResource(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialI18nResource) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialI18nResource:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialI18nResource(*v))
		case []*OfficialI18nResource:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialI18nResource(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialI18nResource) Insert() (pk interface{}, err error) {
	a.Id = 0
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *OfficialI18nResource) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *OfficialI18nResource) GetDiffColumns(old *OfficialI18nResource) (changedCols []interface{}) {

	if old.Id != a.Id {
		changedCols = append(changedCols, `id`)
	}

	if old.Code != a.Code {
		changedCols = append(changedCols, `code`)
	}

	return
}

func (a *OfficialI18nResource) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *OfficialI18nResource) Save(old *OfficialI18nResource, args ...interface{}) (affected int64, err error) {

	if old == nil {
		old = NewOfficialI18nResource(a.Context())
		old.CtxFrom(a)
		if err = old.Get(nil, args...); err != nil {
			return
		}
	}
	changedCols := a.GetDiffColumns(old)
	if len(changedCols) == 0 {
		return
	}
	mw := func(r db.Result) db.Result {
		return r.Select(changedCols...).Limit(1)
	}
	return a.Updatex(mw, args...)
}

func (a *OfficialI18nResource) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialI18nResource) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialI18nResource) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialI18nResource) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialI18nResource) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *OfficialI18nResource) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *OfficialI18nResource) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialI18nResource) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		a.Id = 0
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *OfficialI18nResource) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *OfficialI18nResource) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *OfficialI18nResource) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialI18nResource) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialI18nResource) Reset() *OfficialI18nResource {
	a.Id = 0
	a.Code = ``
	return a
}

func (a *OfficialI18nResource) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["Code"] = a.Code
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "Code":
			r["Code"] = a.Code
		}
	}
	return r
}

func (a *OfficialI18nResource) Clone() *OfficialI18nResource {
	cloned := OfficialI18nResource{Id: a.Id, Code: a.Code}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *OfficialI18nResource) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "id":
			a.Id = param.AsUint(value)
		case "code":
			a.Code = param.AsString(value)
		}
	}
}

func (a *OfficialI18nResource) GetField(field string) interface{} {
	switch field {
	case "Id":
		return a.Id
	case "Code":
		return a.Code
	default:
		return nil
	}
}

func (a *OfficialI18nResource) GetAllFieldNames() []string {
	return []string{
		"Id",
		"Code",
	}
}

func (a *OfficialI18nResource) HasField(field string) bool {
	switch field {
	case "Id":
		return true
	case "Code":
		return true
	default:
		return false
	}
}

func (a *OfficialI18nResource) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint(vv)
		case "Code":
			a.Code = param.AsString(vv)
		}
	}
}

func (a *OfficialI18nResource) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["code"] = a.Code
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "code":
			r["code"] = a.Code
		}
	}
	return r
}

func (a *OfficialI18nResource) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *OfficialI18nResource) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *OfficialI18nResource) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *OfficialI18nResource) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *OfficialI18nResource) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *OfficialI18nResource) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *OfficialI18nResource) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
