// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCustomerOfflinePay = factory.Slicex[*OfficialCustomerOfflinePay]

func NewOfficialCustomerOfflinePay(ctx echo.Context) *OfficialCustomerOfflinePay {
	m := &OfficialCustomerOfflinePay{}
	m.SetContext(ctx)
	return m
}

// OfficialCustomerOfflinePay 客户线下转账信息
type OfficialCustomerOfflinePay struct {
	base    factory.Base
	objects []*OfficialCustomerOfflinePay

	Id               uint64  `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	TargetType       string  `db:"target_type" bson:"target_type" comment:"目标类型" json:"target_type" xml:"target_type"`
	TargetId         uint64  `db:"target_id" bson:"target_id" comment:"目标ID" json:"target_id" xml:"target_id"`
	CustomerId       uint64  `db:"customer_id" bson:"customer_id" comment:"客户ID" json:"customer_id" xml:"customer_id"`
	PayMethod        string  `db:"pay_method" bson:"pay_method" comment:"付款方式" json:"pay_method" xml:"pay_method"`
	PayAccount       string  `db:"pay_account" bson:"pay_account" comment:"付款账号" json:"pay_account" xml:"pay_account"`
	PayAmount        float64 `db:"pay_amount" bson:"pay_amount" comment:"付款金额" json:"pay_amount" xml:"pay_amount"`
	PayBankBranch    string  `db:"pay_bank_branch" bson:"pay_bank_branch" comment:"付款银行支行" json:"pay_bank_branch" xml:"pay_bank_branch"`
	PayTransactionNo string  `db:"pay_transaction_no" bson:"pay_transaction_no" comment:"付款交易订单号" json:"pay_transaction_no" xml:"pay_transaction_no"`
	PayTime          uint    `db:"pay_time" bson:"pay_time" comment:"付款时间" json:"pay_time" xml:"pay_time" form_decoder:"time2unix" form_encoder:"unix2time"`
	PayOwner         string  `db:"pay_owner" bson:"pay_owner" comment:"户主名" json:"pay_owner" xml:"pay_owner"`
	Status           string  `db:"status" bson:"status" comment:"状态(pending-待处理;verified-已核实;invalid-无效)" json:"status" xml:"status"`
	Created          uint    `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created" form_decoder:"time2unix" form_encoder:"unix2time"`
	Updated          uint    `db:"updated" bson:"updated" comment:"更新时间" json:"updated" xml:"updated" form_decoder:"time2unix" form_encoder:"unix2time"`
}

// - base function

func (a *OfficialCustomerOfflinePay) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCustomerOfflinePay) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCustomerOfflinePay) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCustomerOfflinePay) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCustomerOfflinePay) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCustomerOfflinePay) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCustomerOfflinePay) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCustomerOfflinePay) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCustomerOfflinePay) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCustomerOfflinePay) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCustomerOfflinePay) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCustomerOfflinePay) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCustomerOfflinePay) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCustomerOfflinePay) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCustomerOfflinePay) Objects() []*OfficialCustomerOfflinePay {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCustomerOfflinePay) XObjects() Slice_OfficialCustomerOfflinePay {
	return Slice_OfficialCustomerOfflinePay(a.Objects())
}

func (a *OfficialCustomerOfflinePay) NewObjects() factory.Ranger {
	return &Slice_OfficialCustomerOfflinePay{}
}

func (a *OfficialCustomerOfflinePay) InitObjects() *[]*OfficialCustomerOfflinePay {
	a.objects = []*OfficialCustomerOfflinePay{}
	return &a.objects
}

func (a *OfficialCustomerOfflinePay) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCustomerOfflinePay) Short_() string {
	return "official_customer_offline_pay"
}

func (a *OfficialCustomerOfflinePay) Struct_() string {
	return "OfficialCustomerOfflinePay"
}

func (a *OfficialCustomerOfflinePay) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCustomerOfflinePay{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *OfficialCustomerOfflinePay) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *OfficialCustomerOfflinePay) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *OfficialCustomerOfflinePay) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCustomerOfflinePay) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerOfflinePay:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerOfflinePay(*v))
		case []*OfficialCustomerOfflinePay:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerOfflinePay(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerOfflinePay) GroupBy(keyField string, inputRows ...[]*OfficialCustomerOfflinePay) map[string][]*OfficialCustomerOfflinePay {
	var rows Slice_OfficialCustomerOfflinePay
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerOfflinePay(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerOfflinePay(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCustomerOfflinePay) KeyBy(keyField string, inputRows ...[]*OfficialCustomerOfflinePay) map[string]*OfficialCustomerOfflinePay {
	var rows Slice_OfficialCustomerOfflinePay
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerOfflinePay(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerOfflinePay(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCustomerOfflinePay) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCustomerOfflinePay) param.Store {
	var rows Slice_OfficialCustomerOfflinePay
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerOfflinePay(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerOfflinePay(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCustomerOfflinePay) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerOfflinePay:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerOfflinePay(*v))
		case []*OfficialCustomerOfflinePay:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerOfflinePay(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerOfflinePay) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if len(a.TargetType) == 0 {
		a.TargetType = "recharge"
	}
	if len(a.Status) == 0 {
		a.Status = "pending"
	}
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *OfficialCustomerOfflinePay) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.TargetType) == 0 {
		a.TargetType = "recharge"
	}
	if len(a.Status) == 0 {
		a.Status = "pending"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *OfficialCustomerOfflinePay) GetDiffColumns(old *OfficialCustomerOfflinePay) (changedCols []interface{}) {

	if old.Id != a.Id {
		changedCols = append(changedCols, `id`)
	}

	if old.TargetType != a.TargetType {
		changedCols = append(changedCols, `target_type`)
	}

	if old.TargetId != a.TargetId {
		changedCols = append(changedCols, `target_id`)
	}

	if old.CustomerId != a.CustomerId {
		changedCols = append(changedCols, `customer_id`)
	}

	if old.PayMethod != a.PayMethod {
		changedCols = append(changedCols, `pay_method`)
	}

	if old.PayAccount != a.PayAccount {
		changedCols = append(changedCols, `pay_account`)
	}

	if old.PayAmount != a.PayAmount {
		changedCols = append(changedCols, `pay_amount`)
	}

	if old.PayBankBranch != a.PayBankBranch {
		changedCols = append(changedCols, `pay_bank_branch`)
	}

	if old.PayTransactionNo != a.PayTransactionNo {
		changedCols = append(changedCols, `pay_transaction_no`)
	}

	if old.PayTime != a.PayTime {
		changedCols = append(changedCols, `pay_time`)
	}

	if old.PayOwner != a.PayOwner {
		changedCols = append(changedCols, `pay_owner`)
	}

	if old.Status != a.Status {
		changedCols = append(changedCols, `status`)
	}

	if old.Created != a.Created {
		changedCols = append(changedCols, `created`)
	}

	if old.Updated != a.Updated {
		changedCols = append(changedCols, `updated`)
	}

	return
}

func (a *OfficialCustomerOfflinePay) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.TargetType) == 0 {
		a.TargetType = "recharge"
	}
	if len(a.Status) == 0 {
		a.Status = "pending"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *OfficialCustomerOfflinePay) Save(old *OfficialCustomerOfflinePay, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.TargetType) == 0 {
		a.TargetType = "recharge"
	}
	if len(a.Status) == 0 {
		a.Status = "pending"
	}
	if old == nil {
		old = NewOfficialCustomerOfflinePay(a.Context())
		old.CtxFrom(a)
		if err = old.Get(nil, args...); err != nil {
			return
		}
	}
	changedCols := a.GetDiffColumns(old)
	if len(changedCols) == 0 {
		return
	}
	mw := func(r db.Result) db.Result {
		return r.Select(changedCols...).Limit(1)
	}
	return a.Updatex(mw, args...)
}

func (a *OfficialCustomerOfflinePay) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.TargetType) == 0 {
		a.TargetType = "recharge"
	}
	if len(a.Status) == 0 {
		a.Status = "pending"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerOfflinePay) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.TargetType) == 0 {
		a.TargetType = "recharge"
	}
	if len(a.Status) == 0 {
		a.Status = "pending"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerOfflinePay) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerOfflinePay) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerOfflinePay) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["target_type"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["target_type"] = "recharge"
		}
	}
	if val, ok := kvset["status"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["status"] = "pending"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *OfficialCustomerOfflinePay) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["target_type"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["target_type"] = "recharge"
		}
	}
	if val, ok := kvset["status"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["status"] = "pending"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerOfflinePay) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCustomerOfflinePay) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		a.Updated = uint(time.Now().Unix())
		if len(a.TargetType) == 0 {
			a.TargetType = "recharge"
		}
		if len(a.Status) == 0 {
			a.Status = "pending"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if len(a.TargetType) == 0 {
			a.TargetType = "recharge"
		}
		if len(a.Status) == 0 {
			a.Status = "pending"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *OfficialCustomerOfflinePay) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *OfficialCustomerOfflinePay) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *OfficialCustomerOfflinePay) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCustomerOfflinePay) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCustomerOfflinePay) Reset() *OfficialCustomerOfflinePay {
	a.Id = 0
	a.TargetType = ``
	a.TargetId = 0
	a.CustomerId = 0
	a.PayMethod = ``
	a.PayAccount = ``
	a.PayAmount = 0.0
	a.PayBankBranch = ``
	a.PayTransactionNo = ``
	a.PayTime = 0
	a.PayOwner = ``
	a.Status = ``
	a.Created = 0
	a.Updated = 0
	return a
}

func (a *OfficialCustomerOfflinePay) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["TargetType"] = a.TargetType
		r["TargetId"] = a.TargetId
		r["CustomerId"] = a.CustomerId
		r["PayMethod"] = a.PayMethod
		r["PayAccount"] = a.PayAccount
		r["PayAmount"] = a.PayAmount
		r["PayBankBranch"] = a.PayBankBranch
		r["PayTransactionNo"] = a.PayTransactionNo
		r["PayTime"] = a.PayTime
		r["PayOwner"] = a.PayOwner
		r["Status"] = a.Status
		r["Created"] = a.Created
		r["Updated"] = a.Updated
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "TargetType":
			r["TargetType"] = a.TargetType
		case "TargetId":
			r["TargetId"] = a.TargetId
		case "CustomerId":
			r["CustomerId"] = a.CustomerId
		case "PayMethod":
			r["PayMethod"] = a.PayMethod
		case "PayAccount":
			r["PayAccount"] = a.PayAccount
		case "PayAmount":
			r["PayAmount"] = a.PayAmount
		case "PayBankBranch":
			r["PayBankBranch"] = a.PayBankBranch
		case "PayTransactionNo":
			r["PayTransactionNo"] = a.PayTransactionNo
		case "PayTime":
			r["PayTime"] = a.PayTime
		case "PayOwner":
			r["PayOwner"] = a.PayOwner
		case "Status":
			r["Status"] = a.Status
		case "Created":
			r["Created"] = a.Created
		case "Updated":
			r["Updated"] = a.Updated
		}
	}
	return r
}

func (a *OfficialCustomerOfflinePay) Clone() *OfficialCustomerOfflinePay {
	cloned := OfficialCustomerOfflinePay{Id: a.Id, TargetType: a.TargetType, TargetId: a.TargetId, CustomerId: a.CustomerId, PayMethod: a.PayMethod, PayAccount: a.PayAccount, PayAmount: a.PayAmount, PayBankBranch: a.PayBankBranch, PayTransactionNo: a.PayTransactionNo, PayTime: a.PayTime, PayOwner: a.PayOwner, Status: a.Status, Created: a.Created, Updated: a.Updated}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *OfficialCustomerOfflinePay) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "id":
			a.Id = param.AsUint64(value)
		case "target_type":
			a.TargetType = param.AsString(value)
		case "target_id":
			a.TargetId = param.AsUint64(value)
		case "customer_id":
			a.CustomerId = param.AsUint64(value)
		case "pay_method":
			a.PayMethod = param.AsString(value)
		case "pay_account":
			a.PayAccount = param.AsString(value)
		case "pay_amount":
			a.PayAmount = param.AsFloat64(value)
		case "pay_bank_branch":
			a.PayBankBranch = param.AsString(value)
		case "pay_transaction_no":
			a.PayTransactionNo = param.AsString(value)
		case "pay_time":
			a.PayTime = param.AsUint(value)
		case "pay_owner":
			a.PayOwner = param.AsString(value)
		case "status":
			a.Status = param.AsString(value)
		case "created":
			a.Created = param.AsUint(value)
		case "updated":
			a.Updated = param.AsUint(value)
		}
	}
}

func (a *OfficialCustomerOfflinePay) GetField(field string) interface{} {
	switch field {
	case "Id":
		return a.Id
	case "TargetType":
		return a.TargetType
	case "TargetId":
		return a.TargetId
	case "CustomerId":
		return a.CustomerId
	case "PayMethod":
		return a.PayMethod
	case "PayAccount":
		return a.PayAccount
	case "PayAmount":
		return a.PayAmount
	case "PayBankBranch":
		return a.PayBankBranch
	case "PayTransactionNo":
		return a.PayTransactionNo
	case "PayTime":
		return a.PayTime
	case "PayOwner":
		return a.PayOwner
	case "Status":
		return a.Status
	case "Created":
		return a.Created
	case "Updated":
		return a.Updated
	default:
		return nil
	}
}

func (a *OfficialCustomerOfflinePay) GetAllFieldNames() []string {
	return []string{
		"Id",
		"TargetType",
		"TargetId",
		"CustomerId",
		"PayMethod",
		"PayAccount",
		"PayAmount",
		"PayBankBranch",
		"PayTransactionNo",
		"PayTime",
		"PayOwner",
		"Status",
		"Created",
		"Updated",
	}
}

func (a *OfficialCustomerOfflinePay) HasField(field string) bool {
	switch field {
	case "Id":
		return true
	case "TargetType":
		return true
	case "TargetId":
		return true
	case "CustomerId":
		return true
	case "PayMethod":
		return true
	case "PayAccount":
		return true
	case "PayAmount":
		return true
	case "PayBankBranch":
		return true
	case "PayTransactionNo":
		return true
	case "PayTime":
		return true
	case "PayOwner":
		return true
	case "Status":
		return true
	case "Created":
		return true
	case "Updated":
		return true
	default:
		return false
	}
}

func (a *OfficialCustomerOfflinePay) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint64(vv)
		case "TargetType":
			a.TargetType = param.AsString(vv)
		case "TargetId":
			a.TargetId = param.AsUint64(vv)
		case "CustomerId":
			a.CustomerId = param.AsUint64(vv)
		case "PayMethod":
			a.PayMethod = param.AsString(vv)
		case "PayAccount":
			a.PayAccount = param.AsString(vv)
		case "PayAmount":
			a.PayAmount = param.AsFloat64(vv)
		case "PayBankBranch":
			a.PayBankBranch = param.AsString(vv)
		case "PayTransactionNo":
			a.PayTransactionNo = param.AsString(vv)
		case "PayTime":
			a.PayTime = param.AsUint(vv)
		case "PayOwner":
			a.PayOwner = param.AsString(vv)
		case "Status":
			a.Status = param.AsString(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Updated":
			a.Updated = param.AsUint(vv)
		}
	}
}

func (a *OfficialCustomerOfflinePay) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["target_type"] = a.TargetType
		r["target_id"] = a.TargetId
		r["customer_id"] = a.CustomerId
		r["pay_method"] = a.PayMethod
		r["pay_account"] = a.PayAccount
		r["pay_amount"] = a.PayAmount
		r["pay_bank_branch"] = a.PayBankBranch
		r["pay_transaction_no"] = a.PayTransactionNo
		r["pay_time"] = a.PayTime
		r["pay_owner"] = a.PayOwner
		r["status"] = a.Status
		r["created"] = a.Created
		r["updated"] = a.Updated
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "target_type":
			r["target_type"] = a.TargetType
		case "target_id":
			r["target_id"] = a.TargetId
		case "customer_id":
			r["customer_id"] = a.CustomerId
		case "pay_method":
			r["pay_method"] = a.PayMethod
		case "pay_account":
			r["pay_account"] = a.PayAccount
		case "pay_amount":
			r["pay_amount"] = a.PayAmount
		case "pay_bank_branch":
			r["pay_bank_branch"] = a.PayBankBranch
		case "pay_transaction_no":
			r["pay_transaction_no"] = a.PayTransactionNo
		case "pay_time":
			r["pay_time"] = a.PayTime
		case "pay_owner":
			r["pay_owner"] = a.PayOwner
		case "status":
			r["status"] = a.Status
		case "created":
			r["created"] = a.Created
		case "updated":
			r["updated"] = a.Updated
		}
	}
	return r
}

func (a *OfficialCustomerOfflinePay) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *OfficialCustomerOfflinePay) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *OfficialCustomerOfflinePay) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *OfficialCustomerOfflinePay) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *OfficialCustomerOfflinePay) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *OfficialCustomerOfflinePay) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *OfficialCustomerOfflinePay) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
