// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialI18nTranslation = factory.Slicex[*OfficialI18nTranslation]

func NewOfficialI18nTranslation(ctx echo.Context) *OfficialI18nTranslation {
	m := &OfficialI18nTranslation{}
	m.SetContext(ctx)
	return m
}

// OfficialI18nTranslation 多语言译文
type OfficialI18nTranslation struct {
	base    factory.Base
	objects []*OfficialI18nTranslation

	ResourceId uint   `db:"resource_id,pk" bson:"resource_id" comment:"资源ID" json:"resource_id" xml:"resource_id"`
	RowId      uint64 `db:"row_id,pk" bson:"row_id" comment:"数据行ID" json:"row_id" xml:"row_id"`
	Lang       string `db:"lang,pk" bson:"lang" comment:"语种" json:"lang" xml:"lang"`
	Text       string `db:"text" bson:"text" comment:"文本" json:"text" xml:"text"`
}

// - base function

func (a *OfficialI18nTranslation) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialI18nTranslation) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialI18nTranslation) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialI18nTranslation) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialI18nTranslation) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialI18nTranslation) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialI18nTranslation) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialI18nTranslation) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialI18nTranslation) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialI18nTranslation) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialI18nTranslation) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialI18nTranslation) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialI18nTranslation) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialI18nTranslation) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialI18nTranslation) Objects() []*OfficialI18nTranslation {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialI18nTranslation) XObjects() Slice_OfficialI18nTranslation {
	return Slice_OfficialI18nTranslation(a.Objects())
}

func (a *OfficialI18nTranslation) NewObjects() factory.Ranger {
	return &Slice_OfficialI18nTranslation{}
}

func (a *OfficialI18nTranslation) InitObjects() *[]*OfficialI18nTranslation {
	a.objects = []*OfficialI18nTranslation{}
	return &a.objects
}

func (a *OfficialI18nTranslation) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialI18nTranslation) Short_() string {
	return "official_i18n_translation"
}

func (a *OfficialI18nTranslation) Struct_() string {
	return "OfficialI18nTranslation"
}

func (a *OfficialI18nTranslation) Name_() string {
	b := a
	if b == nil {
		b = &OfficialI18nTranslation{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *OfficialI18nTranslation) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *OfficialI18nTranslation) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *OfficialI18nTranslation) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialI18nTranslation) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialI18nTranslation:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialI18nTranslation(*v))
		case []*OfficialI18nTranslation:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialI18nTranslation(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialI18nTranslation) GroupBy(keyField string, inputRows ...[]*OfficialI18nTranslation) map[string][]*OfficialI18nTranslation {
	var rows Slice_OfficialI18nTranslation
	if len(inputRows) > 0 {
		rows = Slice_OfficialI18nTranslation(inputRows[0])
	} else {
		rows = Slice_OfficialI18nTranslation(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialI18nTranslation) KeyBy(keyField string, inputRows ...[]*OfficialI18nTranslation) map[string]*OfficialI18nTranslation {
	var rows Slice_OfficialI18nTranslation
	if len(inputRows) > 0 {
		rows = Slice_OfficialI18nTranslation(inputRows[0])
	} else {
		rows = Slice_OfficialI18nTranslation(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialI18nTranslation) AsKV(keyField string, valueField string, inputRows ...[]*OfficialI18nTranslation) param.Store {
	var rows Slice_OfficialI18nTranslation
	if len(inputRows) > 0 {
		rows = Slice_OfficialI18nTranslation(inputRows[0])
	} else {
		rows = Slice_OfficialI18nTranslation(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialI18nTranslation) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialI18nTranslation:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialI18nTranslation(*v))
		case []*OfficialI18nTranslation:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialI18nTranslation(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialI18nTranslation) Insert() (pk interface{}, err error) {

	if len(a.Lang) == 0 {
		a.Lang = "en"
	}
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()

	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *OfficialI18nTranslation) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if len(a.Lang) == 0 {
		a.Lang = "en"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *OfficialI18nTranslation) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if len(a.Lang) == 0 {
		a.Lang = "en"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *OfficialI18nTranslation) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {

	if len(a.Lang) == 0 {
		a.Lang = "en"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialI18nTranslation) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {

	if len(a.Lang) == 0 {
		a.Lang = "en"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialI18nTranslation) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialI18nTranslation) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialI18nTranslation) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["lang"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["lang"] = "en"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *OfficialI18nTranslation) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["lang"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["lang"] = "en"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *OfficialI18nTranslation) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialI18nTranslation) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		if len(a.Lang) == 0 {
			a.Lang = "en"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		if len(a.Lang) == 0 {
			a.Lang = "en"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})

	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *OfficialI18nTranslation) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *OfficialI18nTranslation) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *OfficialI18nTranslation) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialI18nTranslation) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialI18nTranslation) Reset() *OfficialI18nTranslation {
	a.ResourceId = 0
	a.RowId = 0
	a.Lang = ``
	a.Text = ``
	return a
}

func (a *OfficialI18nTranslation) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["ResourceId"] = a.ResourceId
		r["RowId"] = a.RowId
		r["Lang"] = a.Lang
		r["Text"] = a.Text
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "ResourceId":
			r["ResourceId"] = a.ResourceId
		case "RowId":
			r["RowId"] = a.RowId
		case "Lang":
			r["Lang"] = a.Lang
		case "Text":
			r["Text"] = a.Text
		}
	}
	return r
}

func (a *OfficialI18nTranslation) Clone() *OfficialI18nTranslation {
	cloned := OfficialI18nTranslation{ResourceId: a.ResourceId, RowId: a.RowId, Lang: a.Lang, Text: a.Text}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *OfficialI18nTranslation) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "resource_id":
			a.ResourceId = param.AsUint(value)
		case "row_id":
			a.RowId = param.AsUint64(value)
		case "lang":
			a.Lang = param.AsString(value)
		case "text":
			a.Text = param.AsString(value)
		}
	}
}

func (a *OfficialI18nTranslation) GetField(field string) interface{} {
	switch field {
	case "ResourceId":
		return a.ResourceId
	case "RowId":
		return a.RowId
	case "Lang":
		return a.Lang
	case "Text":
		return a.Text
	default:
		return nil
	}
}

func (a *OfficialI18nTranslation) GetAllFieldNames() []string {
	return []string{
		"ResourceId",
		"RowId",
		"Lang",
		"Text",
	}
}

func (a *OfficialI18nTranslation) HasField(field string) bool {
	switch field {
	case "ResourceId":
		return true
	case "RowId":
		return true
	case "Lang":
		return true
	case "Text":
		return true
	default:
		return false
	}
}

func (a *OfficialI18nTranslation) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "ResourceId":
			a.ResourceId = param.AsUint(vv)
		case "RowId":
			a.RowId = param.AsUint64(vv)
		case "Lang":
			a.Lang = param.AsString(vv)
		case "Text":
			a.Text = param.AsString(vv)
		}
	}
}

func (a *OfficialI18nTranslation) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["resource_id"] = a.ResourceId
		r["row_id"] = a.RowId
		r["lang"] = a.Lang
		r["text"] = a.Text
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "resource_id":
			r["resource_id"] = a.ResourceId
		case "row_id":
			r["row_id"] = a.RowId
		case "lang":
			r["lang"] = a.Lang
		case "text":
			r["text"] = a.Text
		}
	}
	return r
}

func (a *OfficialI18nTranslation) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *OfficialI18nTranslation) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *OfficialI18nTranslation) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *OfficialI18nTranslation) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *OfficialI18nTranslation) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *OfficialI18nTranslation) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *OfficialI18nTranslation) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
